// 캐릭터/무기/에코 "목록"은 자주 안 바뀌고 용량도 작아서 fetch 없이 그냥 JS로 둠.
// (파일을 서버 없이 더블클릭으로 열면 fetch가 CORS로 막히기 때문 — index.html을 file://로 열어도 항상 동작해야 함)
// 반대로 캐릭터/무기/에코 "상세 데이터"(스킬 계수 등)는 양이 많아지므로 js/main.js의 loadCharacterDetail 등에서
// data/characters/<id>.json 처럼 필요할 때만 fetch로 불러옴 — 이 경우엔 로컬 서버(npm run serve)로 열어야 함.
//
// weaponType: 'sword'(직검) | 'broadblade'(대검) | 'pistols'(권총) | 'gauntlets'(권갑) | 'rectifier'(증폭기)
// null인 항목은 확신이 없어서 비워둠 — 확인 후 채워주세요.
//
// modes: 전투 중 속성을 전환할 수 있는 캐릭터의 모드 목록(예: 린네 파동/밀집, 에이메스 파동/불꽃). 없으면 null.
// 이것도 아는 캐릭터만 채워뒀고 나머지는 확인 필요.

const characters = [
  { id: 'hsin', name: '여우의별자리', weaponType: 'rectifier', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/hsin.png' },
  { id: 'qingxiao', name: '청초', weaponType: 'sword', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/qingxiao.png' },
  { id: 'jingran', name: '경연', weaponType: 'broadblade', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/jingran.png' },
  { id: 'suoming', name: '쇄명', weaponType: 'sword', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/suoming.png' },
  { id: 'suisui', name: '수수', weaponType: 'rectifier', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/suisui.png' },
  { id: 'yangyang-xuanling', name: '양양:현령', weaponType: 'sword', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/yangyang-xuanling.png' },
  { id: 'lucilla', name: '루실라', weaponType: 'rectifier', element: '응결', modes: ["서리","에코"], image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lucilla.png' },
  { id: 'rebecca', name: '레베카', weaponType: 'pistols', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/rebecca.png' },
  { id: 'lucy', name: '루시', weaponType: 'pistols', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lucy.png' },
  { id: 'denia', name: '데니아', weaponType: 'rectifier', element: '용융', modes: ["불꽃","밀집"], image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/denia.png' },
  { id: 'hiyuki', name: '히유키', weaponType: 'sword', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/hiyuki.png' },
  { id: 'sigrika', name: '시그리카', weaponType: 'gauntlets', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/sigrika.png' },
  { id: 'luuk-herssen', name: '루크', weaponType: 'gauntlets', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/luuk-herssen.png' },
  { id: 'aemeath', name: '에이메스', weaponType: 'sword', element: '용융', modes: ["파동","불꽃"], image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/aemeath.png' },
  { id: 'mornye', name: '모니에', weaponType: 'broadblade', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/mornye.png' },
  { id: 'lynae', name: '린네', weaponType: 'pistols', element: '회절', modes: ["파동","밀집"], image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lynae.png' },
  { id: 'buling', name: '복링', weaponType: 'rectifier', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/buling.png' },
  { id: 'chisa', name: '치사', weaponType: 'broadblade', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/chisa.png' },
  { id: 'qiuyuan', name: '구원', weaponType: 'sword', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/qiuyuan.png' },
  { id: 'galbrena', name: '갈브레나', weaponType: 'pistols', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/galbrena.png' },
  { id: 'iuno', name: '유노', weaponType: 'gauntlets', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/iuno.png' },
  { id: 'augusta', name: '아우구스타', weaponType: 'broadblade', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/augusta.png' },
  { id: 'phrolova', name: '플로로', weaponType: 'rectifier', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/phrolova.png' },
  { id: 'lupa', name: '루파', weaponType: 'broadblade', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lupa.png' },
  { id: 'cartethyia', name: '카르티시아', weaponType: 'sword', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/cartethyia.png' },
  { id: 'ciaccona', name: '샤콘', weaponType: 'pistols', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/ciaccona.png' },
  { id: 'zani', name: '젠니', weaponType: 'gauntlets', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/zani.png' },
  { id: 'rover-1', name: '방랑자 [기류]', weaponType: 'sword', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/rover.png' },
  { id: 'cantarella', name: '칸타렐라', weaponType: 'rectifier', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/cantarella.png' },
  { id: 'brant', name: '브렌트', weaponType: 'sword', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/brant.png' },
  { id: 'phoebe', name: '페비', weaponType: 'rectifier', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/phoebe.png' },
  { id: 'roccia', name: '로코코', weaponType: 'gauntlets', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/roccia.png' },
  { id: 'carlotta', name: '카를로타', weaponType: 'pistols', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/carlotta.png' },
  { id: 'lumi', name: '루미', weaponType: 'broadblade', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lumi.png' },
  { id: 'camellya', name: '카멜리아', weaponType: 'sword', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/camellya.png' },
  { id: 'youhu', name: '유호', weaponType: 'gauntlets', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/youhu.png' },
  { id: 'shorekeeper', name: '파수인', weaponType: 'rectifier', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/shorekeeper.png' },
  { id: 'xiangli-yao', name: '상리요', weaponType: 'gauntlets', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/xiangli-yao.png' },
  { id: 'zhezhi', name: '절지', weaponType: 'rectifier', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/zhezhi.png' },
  { id: 'changli', name: '장리', weaponType: 'sword', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/changli.png' },
  { id: 'jinhsi', name: '금희', weaponType: 'broadblade', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/jinhsi.png' },
  { id: 'yuanwu', name: '연무', weaponType: 'gauntlets', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/yuanwu.png' },
  { id: 'yangyang', name: '양양', weaponType: 'sword', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/yangyang.png' },
  { id: 'taoqi', name: '도기', weaponType: 'broadblade', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/taoqi.png' },
  { id: 'sanhua', name: '산화', weaponType: 'sword', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/sanhua.png' },
  { id: 'mortefi', name: '모르테피', weaponType: 'pistols', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/mortefi.png' },
  { id: 'danjin', name: '단근', weaponType: 'sword', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/danjin.png' },
  { id: 'chixia', name: '치샤', weaponType: 'pistols', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/chixia.png' },
  { id: 'baizhi', name: '설지', weaponType: 'rectifier', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/baizhi.png' },
  { id: 'aalto', name: '알토', weaponType: 'pistols', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/aalto.png' },
  { id: 'verina', name: '벨리나', weaponType: 'rectifier', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/verina.png' },
  { id: 'lingyang', name: '능양', weaponType: 'gauntlets', element: '응결', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/lingyang.png' },
  { id: 'jianxin', name: '감심', weaponType: 'gauntlets', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/jianxin.png' },
  { id: 'encore', name: '앙코', weaponType: 'rectifier', element: '용융', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/encore.png' },
  { id: 'calcharo', name: '카카루', weaponType: 'broadblade', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/calcharo.png' },
  { id: 'rover-2', name: '방랑자 [회절]', weaponType: 'sword', element: '회절', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/rover.png' },
  { id: 'rover-3', name: '방랑자 [인멸]', weaponType: 'sword', element: '인멸', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/rover.png' },
  { id: 'yinlin', name: '음림', weaponType: 'rectifier', element: '전도', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/yinlin.png' },
  { id: 'jiyan', name: '기염', weaponType: 'broadblade', element: '기류', modes: null, image: 'https://arufuzgxjgjbjlgddrdo.supabase.co/storage/v1/object/public/images/characters/jiyan.png' },
];

// 공명 효율/크리티컬/크리티컬 피해는 모든 캐릭터가 동일한 기본값을 가지므로
// 캐릭터별 baseStats에 안 넣고 여기서 한 번만 관리함. 지금은 전부 0(자리만 잡아둠).
const COMMON_BASE_STATS = {
  energyRegen: 100,
  critRate: 5,
  critDmg: 150,
};

const weapons = [
  { id: 'broadblade-01', name: '푸른물결의 빛', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-02', name: '에너지 절단', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-03', name: '청룡의 천장', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-04', name: '태평성대', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-05', name: '불길', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-06', name: '천둥벼락을 다스리는 권능', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-07', name: '쿠모키리', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-08', name: '별하늘 연산 측정기', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-09', name: '수많은 인도', weaponType: 'broadblade', rarity: 5 },
  { id: 'broadblade-10', name: '장야의 불빛', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-11', name: '기묘한 울림', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-12', name: '저무는 동녘', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-13', name: '멸망의 주파수', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-14', name: '가을의 무늬', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-15', name: '금빛 하늘', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-16', name: '41형 대검 · 무거운 책임', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-17', name: '용서의 명상록', weaponType: 'broadblade', rarity: 4 },
  { id: 'broadblade-18', name: '흑야의 대검 · 현명', weaponType: 'broadblade', rarity: 3 },
  { id: 'broadblade-19', name: '수행자의 대검 · 벽로', weaponType: 'broadblade', rarity: 3 },
  { id: 'broadblade-20', name: '원능의 대검 · 견습I', weaponType: 'broadblade', rarity: 3 },
  { id: 'broadblade-21', name: '수호자의 대검 · 근성', weaponType: 'broadblade', rarity: 3 },
  { id: 'broadblade-22', name: '천상의 음률', weaponType: 'broadblade', rarity: 3 },
  { id: 'broadblade-23', name: '태초의 대검', weaponType: 'broadblade', rarity: 2 },
  { id: 'broadblade-24', name: '견습용 대검', weaponType: 'broadblade', rarity: 1 },
  { id: 'sword-01', name: '천년의 회류', weaponType: 'sword', rarity: 5 },
  { id: 'sword-02', name: '레이저 변형', weaponType: 'sword', rarity: 5 },
  { id: 'sword-03', name: '솟아오르는 화염', weaponType: 'sword', rarity: 5 },
  { id: 'sword-04', name: '날카로운 봄', weaponType: 'sword', rarity: 5 },
  { id: 'sword-05', name: '흔들리지 않는 용기', weaponType: 'sword', rarity: 5 },
  { id: 'sword-06', name: '숙명에 맞서는 관', weaponType: 'sword', rarity: 5 },
  { id: 'sword-07', name: '푸른 의지', weaponType: 'sword', rarity: 5 },
  { id: 'sword-08', name: '영원한 샛별', weaponType: 'sword', rarity: 5 },
  { id: 'sword-09', name: '서린 불꽃', weaponType: 'sword', rarity: 5 },
  { id: 'sword-10', name: '아득히 푸른 하늘', weaponType: 'sword', rarity: 5 },
  { id: 'sword-11', name: '옥빛 구름', weaponType: 'sword', rarity: 5 },
  { id: 'sword-12', name: '혈맹의 약속', weaponType: 'sword', rarity: 5 },
  { id: 'sword-13', name: '야귀의 신념', weaponType: 'sword', rarity: 4 },
  { id: 'sword-14', name: '행진의 서곡', weaponType: 'sword', rarity: 4 },
  { id: 'sword-15', name: '상승의 서녘', weaponType: 'sword', rarity: 4 },
  { id: 'sword-16', name: '영원의 붕괴', weaponType: 'sword', rarity: 4 },
  { id: 'sword-17', name: '천공의 광경', weaponType: 'sword', rarity: 4 },
  { id: 'sword-18', name: '예리한 날개깃', weaponType: 'sword', rarity: 4 },
  { id: 'sword-19', name: '18형 직검 · 순간의 칼빛', weaponType: 'sword', rarity: 4 },
  { id: 'sword-20', name: '풍류의 우화시', weaponType: 'sword', rarity: 4 },
  { id: 'sword-21', name: '마음의 닻', weaponType: 'sword', rarity: 4 },
  { id: 'sword-22', name: '흑야의 직검 · 흑뢰', weaponType: 'sword', rarity: 3 },
  { id: 'sword-23', name: '수행자의 직검 · 행적', weaponType: 'sword', rarity: 3 },
  { id: 'sword-24', name: '원능의 직검 · 견습II', weaponType: 'sword', rarity: 3 },
  { id: 'sword-25', name: '수호자의 직검 · 기민', weaponType: 'sword', rarity: 3 },
  { id: 'sword-26', name: '태초의 직검', weaponType: 'sword', rarity: 2 },
  { id: 'sword-27', name: '견습용 직검', weaponType: 'sword', rarity: 1 },
  { id: 'pistols-01', name: '부동의 안개', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-02', name: '위상의 파동', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-03', name: '죽음과 춤', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-04', name: '숲속의 아리아', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-05', name: '얽혀진 빛과 그림자', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-06', name: '스펙트럼 블래스터', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-07', name: '스펙트럴 트리거', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-08', name: '스컬 스래셔', weaponType: 'pistols', rarity: 5 },
  { id: 'pistols-09', name: '불멸의 성화', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-10', name: '화려한 악곡', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-11', name: '천공의 순간', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-12', name: '역설의 격류', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-13', name: '뇌전', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-14', name: '태양 불꽃', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-15', name: '26형 권총 · 맹렬한 돌격', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-16', name: '작별의 로맨스', weaponType: 'pistols', rarity: 4 },
  { id: 'pistols-17', name: '흑야의 권총 · 흑성', weaponType: 'pistols', rarity: 3 },
  { id: 'pistols-18', name: '수행자의 권총 · 통찰', weaponType: 'pistols', rarity: 3 },
  { id: 'pistols-19', name: '원능의 권총 · 견습III', weaponType: 'pistols', rarity: 3 },
  { id: 'pistols-20', name: '수호자의 권총 · 용맹', weaponType: 'pistols', rarity: 3 },
  { id: 'pistols-21', name: '태초의 권총', weaponType: 'pistols', rarity: 2 },
  { id: 'pistols-22', name: '견습용 권총', weaponType: 'pistols', rarity: 1 },
  { id: 'gauntlets-01', name: '물결의 파동', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-02', name: '격동의 조력', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-03', name: '팔방의 천추', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-04', name: '희비극', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-05', name: '불빛의 심판', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-06', name: '세상 만물의 진리', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-07', name: '한낮의 의지', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-08', name: '솔스원의 해석', weaponType: 'gauntlets', rarity: 5 },
  { id: 'gauntlets-09', name: '전우의 의리', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-10', name: '바람의 악센트', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-11', name: '천공의 역행', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-12', name: '천상의 나선', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-13', name: '황금 권갑', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-14', name: '거침없는 비상', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-15', name: '21형 권갑 · 아이언 팬텀', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-16', name: '만취의 영웅지', weaponType: 'gauntlets', rarity: 4 },
  { id: 'gauntlets-17', name: '흑야의 권갑 · 흑빛', weaponType: 'gauntlets', rarity: 3 },
  { id: 'gauntlets-18', name: '수행자의 권갑 · 파괴', weaponType: 'gauntlets', rarity: 3 },
  { id: 'gauntlets-19', name: '원능의 권갑 · 견습IV', weaponType: 'gauntlets', rarity: 3 },
  { id: 'gauntlets-20', name: '수호자의 권갑 · 강력', weaponType: 'gauntlets', rarity: 3 },
  { id: 'gauntlets-21', name: '태초의 권갑', weaponType: 'gauntlets', rarity: 2 },
  { id: 'gauntlets-22', name: '견습용 권갑', weaponType: 'gauntlets', rarity: 1 },
  { id: 'rectifier-01', name: '파도의 기록', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-02', name: '보손 관측기', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-03', name: '꼭두각시의 손', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-04', name: '옥수 비단', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-05', name: '뭇별의 교향곡', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-06', name: '광휘의 찬송가', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-07', name: '바다의 속삭임', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-08', name: '잊혀진 피안의 슬픈 악장', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-09', name: '위조된 작은별', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-10', name: '프리즈 프레임', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-11', name: '노을에 깃든 이슬', weaponType: 'rectifier', rarity: 5 },
  { id: 'rectifier-12', name: '금주의 수호', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-13', name: '판타지 변주', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-14', name: '굉음', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-15', name: '융합의 원반', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-16', name: '청음', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-17', name: '눈부신 빛', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-18', name: '25형 증폭기 · 울림의 멜로디', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-19', name: '허위의 왈츠', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-20', name: '심해의 메아리', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-21', name: '바다의 선물', weaponType: 'rectifier', rarity: 4 },
  { id: 'rectifier-22', name: '흑야의 증폭기 · 흑광', weaponType: 'rectifier', rarity: 3 },
  { id: 'rectifier-23', name: '수행자의 증폭기 · 탐색', weaponType: 'rectifier', rarity: 3 },
  { id: 'rectifier-24', name: '원능의 증폭기 · 견습V', weaponType: 'rectifier', rarity: 3 },
  { id: 'rectifier-25', name: '수호자의 증폭기 · 모략', weaponType: 'rectifier', rarity: 3 },
  { id: 'rectifier-26', name: '태초의 증폭기', weaponType: 'rectifier', rarity: 2 },
  { id: 'rectifier-27', name: '견습용 증폭기', weaponType: 'rectifier', rarity: 1 },
];

// 실제 에코 목록(메인 에코 선택용)은 나중에 채움.
// weapons와 같은 패턴: 각 에코가 자기 세트/코스트를 속성으로 들고 있어서
// echoes.filter(e => e.setId === setId && e.cost === cost) 로 바로 필터링됨.
// 예시: { id: 'yuanwu', name: '원무 시녀', setId: '야밤의 서리', cost: 4 }
const echoes = [];

// 에코 세트(소나타 효과) 목록
const echoSets = [
  '야밤의 서리', '솟구치는 용암', '울려퍼지는 뇌음', '스쳐가는 바람', '빛나는 별', '빛을 삼키는 해',
  '찬란한 광휘', '떠오르는 구름', '끊임없는 잔향', '냉철한 결단', '영원의 광채', '어둠의 장막',
  '하늘의 합주곡', '파도에 맞선 용기', '끝없는 하늘', '영광이 깃든 바람', '울부짖는 늑대의 불꽃',
  '뒤틀린 피안의 꿈', '영광의 칼날로 만들어진 왕관', '만물의 숨결에 비롯된 울림',
  '불타는 깃털을 펼친 사냥꾼의 그림자', '운명을 붕괴시키는 현', '역광 속 눈부신 서약',
  '빛을 쫓는 별의 고리', '흐르는 금빛 속 진리의 답', '긴 여정을 떠나는 별', '오색찬란한 거품',
  '함의의 소리를 따라', '소리 없이 내려앉은 기도의 눈', '마음을 엮은 꿈의 그림자',
  '꿈을 깨뜨리는 망령의 악몽', '내려앉은 깃털의 노래', '악을 씻어내는 마음', '황천길을 밝히는 등불',
];

// 코스트(4/3/1)별로 고를 수 있는 주옵션 목록
const echoMainStatsByCost = {
  4: ['공격력', 'HP', '방어력', '크리티컬', '크리티컬 피해', '치료 효과 보너스'],
  3: ['공격력', 'HP', '방어력', '용융 피해 보너스', '응결 피해 보너스', '전도 피해 보너스', '기류 피해 보너스', '회절 피해 보너스', '인멸 피해 보너스', '공명 효율'],
  1: ['공격력', 'HP', '방어력'],
};

// 부옵션별로 고를 수 있는 수치 목록 (퍼센트 스탯은 ECHO_FLAT_SUBSTATS에 없는 것들)
const echoSubStatValues = {
  '크리티컬': [6.3, 6.9, 7.5, 8.1, 8.7, 9.3, 9.9, 10.5],
  '크리티컬 피해': [12.6, 13.8, 15, 16.2, 17.4, 18.6, 19.8, 21],
  '공명 효율': [6.8, 7.6, 8.4, 9.2, 10, 10.8, 11.6, 12.4],
  '방어력(%)': [8.1, 9, 10, 10.9, 11.8, 12.8, 13.8, 14.7],
  '일반 공격 피해 보너스': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  '강공격 피해 보너스': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  '공명 스킬 피해 보너스': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  '공명 해방 피해 보너스': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  '공격력(%)': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  'HP(%)': [6.4, 7.1, 7.9, 8.6, 9.4, 10.1, 10.9, 11.6],
  'HP': [320, 360, 390, 430, 470, 510, 540, 580],
  '공격력': [30, 40, 50, 60],
  '방어력': [40, 50, 60, 70],
};
const echoSubStatNames = Object.keys(echoSubStatValues);
const ECHO_FLAT_SUBSTATS = ['HP', '공격력', '방어력']; // 얘네만 %가 아니라 그냥 수치
